# Generated by Django 2.2 on 2020-07-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilot',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters'),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='script',
            field=models.FileField(blank=True, null=True, upload_to='scipts'),
        ),
    ]
