# Generated by Django 2.2 on 2020-07-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script_app', '0002_auto_20200725_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilot',
            name='script',
            field=models.FileField(blank=True, null=True, upload_to='scripts'),
        ),
    ]
