# Generated by Django 2.2 on 2020-08-27 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script_app', '0003_auto_20200729_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilot',
            name='poster',
            field=models.ImageField(blank=True, default='default.png', upload_to='posters'),
        ),
    ]
