# Generated by Django 2.2 on 2020-08-29 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script_app', '0005_auto_20200829_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilot',
            name='poster',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='posters'),
        ),
    ]
