# Generated by Django 3.1.2 on 2020-10-13 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('script_app', '0007_auto_20201008_0420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pilot',
            options={},
        ),
    ]
