# Generated by Django 3.1.2 on 2020-10-14 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script_app', '0008_auto_20201013_0315'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
