# Generated by Django 3.1.2 on 2020-10-15 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('script_app', '0009_commentform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentForm',
            new_name='Comment',
        ),
    ]
