# Generated by Django 3.1.2 on 2020-10-15 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('script_app', '0010_auto_20201015_0407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='subject',
        ),
    ]
