# Generated by Django 4.0.1 on 2022-01-06 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script_app', '0013_creator_show_tag_delete_pilot_show_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='creator',
            name='last_name',
        ),
        migrations.AddField(
            model_name='creator',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
