# Generated by Django 4.0.1 on 2022-01-06 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script_app', '0014_remove_creator_first_name_remove_creator_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='creator',
        ),
        migrations.AddField(
            model_name='show',
            name='creators',
            field=models.ManyToManyField(related_name='shows', to='script_app.Creator'),
        ),
    ]
