# Generated by Django 4.0.1 on 2022-01-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script_app', '0015_remove_show_creator_show_creators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='script',
            field=models.FileField(blank=True, null=True, upload_to='screenplays'),
        ),
    ]
