# Generated by Django 3.1.5 on 2022-11-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script_app', '0016_alter_show_script'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='tag',
            field=models.ManyToManyField(related_name='tag', to='script_app.Tag'),
        ),
    ]
