# Generated by Django 3.1.5 on 2022-11-04 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script_app', '0017_auto_20221104_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='tag',
            field=models.ManyToManyField(related_name='tags', to='script_app.Tag'),
        ),
    ]
